# Generated by Django 4.0.4 on 2022-05-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_surname', models.CharField(max_length=50)),
                ('u_name', models.CharField(max_length=50)),
                ('u_mail', models.EmailField(max_length=254)),
                ('u_password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_price', models.FloatField()),
                ('p_amount', models.IntegerField()),
                ('p_description', models.CharField(max_length=100)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacture')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField()),
                ('date', models.DateField()),
                ('o_amount', models.IntegerField()),
                ('o_price', models.FloatField()),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacture')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.user')),
            ],
        ),
    ]
