# Generated by Django 4.0.4 on 2022-05-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='m_id',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='p_id',
            new_name='p',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='s_id',
            new_name='s',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='u_id',
            new_name='u',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='c_id',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='m_id',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='s_id',
            new_name='s',
        ),
    ]
