# Generated by Django 4.0.4 on 2022-06-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_c_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='m',
        ),
        migrations.RemoveField(
            model_name='order',
            name='s',
        ),
        migrations.RemoveField(
            model_name='product',
            name='m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='s',
        ),
        migrations.AddField(
            model_name='product',
            name='p_photo',
            field=models.BinaryField(null=True),
        ),
        migrations.DeleteModel(
            name='Manufacture',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
