# Generated by Django 4.0.4 on 2022-06-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_p_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='c_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='c',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='p',
        ),
        migrations.RemoveField(
            model_name='order',
            name='u',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customer'),
        ),
    ]
